# Generated by Django 5.0.6 on 2024-06-07 15:41

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('id', models.UUIDField(default=uuid.UUID('3e5a35ed-9035-4456-a655-2792d1c546b7'), primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('html', models.TextField(db_column='html')),
            ],
            options={
                'db_table': 'MAE_TEMPLATE',
            },
        ),
    ]
