version: "2"

services:
  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/src/mediafields

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672

  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/server-entrypoint.sh
    volumes:
      - static_volume:/app/backend/src/mediafields
    expose:
      - 8000
    env_file:
      - ./backend/src/environment/.env.production

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/worker-entrypoint.sh
    volumes:
      - static_volume:/app/backend/src/mediafields
    env_file:
      - ./backend/src/environment/.env.production
    depends_on:
      - server
      - redis
      - rabbitmq

  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/src/environment/.env.production
    expose:
      - 5432

volumes:
  static_volume: {}
  postgres_data: {}
