version: "2"

# sudo service apache2 stop
# sudo systemctl stop rabbitmq-server.service

services:
  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/src/mediafields

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    depends_on:
      - nginx

  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/src/environment/.env.production
    expose:
      - 5432
    depends_on:
      - nginx

  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/server-entrypoint.sh
    volumes:
      - static_volume:/app/backend/src/mediafields
    expose:
      - 8000
    env_file:
      - ./backend/src/environment/.env.production
    depends_on:
      - db
      - redis

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:latest
    env_file:
      - ./backend/src/environment/.env.production
    expose:
      - 5672
    network_mode: "host"
    depends_on:
      - server

  celery:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/worker-entrypoint.sh
    volumes:
      - static_volume:/app/backend/src/mediafields
    depends_on:
      rabbitmq:
        condition: service_started
    network_mode: "host"

volumes:
  static_volume: {}
  postgres_data: {}
