# Generated by Django 5.0.6 on 2024-06-28 20:12

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("57aba32e-0a5e-4480-8832-085e3267c6b6"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=50)),
            ],
            options={
                "db_table": "MAE_COLOR",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("57aba32e-0a5e-4480-8832-085e3267c6b6"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                ("upload", models.ImageField(upload_to="products/%Y/%m/%d/")),
            ],
            options={
                "db_table": "MAE_IMAGE",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("57aba32e-0a5e-4480-8832-085e3267c6b6"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=50)),
            ],
            options={
                "db_table": "MAE_SIZE",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("57aba32e-0a5e-4480-8832-085e3267c6b6"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        db_column="total", decimal_places=2, default=0, max_digits=19
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "MAE_BILL",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("57aba32e-0a5e-4480-8832-085e3267c6b6"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "originalPrice",
                    models.DecimalField(
                        db_column="original_price", decimal_places=2, max_digits=19
                    ),
                ),
                (
                    "discountPrice",
                    models.DecimalField(
                        db_column="discount_price", decimal_places=2, max_digits=19
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        db_column="color",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="msproduct.color",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        db_column="size",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="msproduct.size",
                    ),
                ),
            ],
            options={
                "db_table": "MAE_PRICE",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("57aba32e-0a5e-4480-8832-085e3267c6b6"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        db_column="price",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="msproduct.price",
                    ),
                ),
            ],
            options={
                "db_table": "MAE_PRODUCT",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("57aba32e-0a5e-4480-8832-085e3267c6b6"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        db_column="quantity",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        db_column="total", decimal_places=2, max_digits=19
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        db_column="bill",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="msproduct.bill",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="msproduct.product",
                    ),
                ),
            ],
            options={
                "db_table": "MAE_ITEM",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("57aba32e-0a5e-4480-8832-085e3267c6b6"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        db_column="image",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="msproduct.image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="msproduct.product",
                    ),
                ),
            ],
            options={
                "db_table": "MAE_PRODUCT_IMAGE",
            },
        ),
    ]
