# Generated by Django 5.0.6 on 2024-07-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msproduct", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="product",
        ),
    ]
