# Generated by Django 5.0.6 on 2024-06-28 21:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msproduct", "0002_alter_bill_id_alter_color_id_alter_image_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b5cb4369-5b7a-4cc7-bb1d-9f27cc81d87d"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b5cb4369-5b7a-4cc7-bb1d-9f27cc81d87d"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b5cb4369-5b7a-4cc7-bb1d-9f27cc81d87d"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b5cb4369-5b7a-4cc7-bb1d-9f27cc81d87d"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b5cb4369-5b7a-4cc7-bb1d-9f27cc81d87d"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b5cb4369-5b7a-4cc7-bb1d-9f27cc81d87d"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b5cb4369-5b7a-4cc7-bb1d-9f27cc81d87d"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="size",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b5cb4369-5b7a-4cc7-bb1d-9f27cc81d87d"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
    ]
