# Generated by Django 5.0.6 on 2024-07-02 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msproduct", "0003_alter_bill_id_alter_color_id_alter_image_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("743be708-464d-4c13-a881-2c3cdb4f4de2"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("743be708-464d-4c13-a881-2c3cdb4f4de2"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("743be708-464d-4c13-a881-2c3cdb4f4de2"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("743be708-464d-4c13-a881-2c3cdb4f4de2"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("743be708-464d-4c13-a881-2c3cdb4f4de2"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("743be708-464d-4c13-a881-2c3cdb4f4de2"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("743be708-464d-4c13-a881-2c3cdb4f4de2"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="size",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("743be708-464d-4c13-a881-2c3cdb4f4de2"),
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
    ]
