# Generated by Django 5.0.6 on 2024-07-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msproduct", "0005_alter_bill_id_alter_color_id_alter_image_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="total",
        ),
    ]
