# Generated by Django 5.0.6 on 2024-05-30 20:37

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c625f2d8-6b2b-4efd-b9bf-c72e1e9172df'), primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'MAE_BILL',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c625f2d8-6b2b-4efd-b9bf-c72e1e9172df'), primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_column='name', max_length=50)),
            ],
            options={
                'db_table': 'MAE_COLOR',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c625f2d8-6b2b-4efd-b9bf-c72e1e9172df'), primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('upload', models.ImageField(upload_to='products/% Y/% m/% d/')),
            ],
            options={
                'db_table': 'MAE_IMAGE',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c625f2d8-6b2b-4efd-b9bf-c72e1e9172df'), primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_column='name', max_length=50)),
            ],
            options={
                'db_table': 'MAE_SIZE',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c625f2d8-6b2b-4efd-b9bf-c72e1e9172df'), primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('originalPrice', models.DecimalField(db_column='original_price', decimal_places=2, max_digits=19)),
                ('discountPrice', models.DecimalField(db_column='discount_price', decimal_places=2, max_digits=19)),
                ('color', models.ForeignKey(db_column='color', on_delete=django.db.models.deletion.CASCADE, to='msproduct.color')),
                ('size', models.ForeignKey(db_column='size', on_delete=django.db.models.deletion.CASCADE, to='msproduct.size')),
            ],
            options={
                'db_table': 'MAE_PRICE',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c625f2d8-6b2b-4efd-b9bf-c72e1e9172df'), primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('price', models.ForeignKey(db_column='price', on_delete=django.db.models.deletion.CASCADE, to='msproduct.price')),
            ],
            options={
                'db_table': 'MAE_PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c625f2d8-6b2b-4efd-b9bf-c72e1e9172df'), primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('quantity', models.IntegerField(db_column='quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=19)),
                ('bill', models.ForeignKey(db_column='bill', null=True, on_delete=django.db.models.deletion.CASCADE, to='msproduct.bill')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='msproduct.product')),
            ],
            options={
                'db_table': 'MAE_ITEM',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c625f2d8-6b2b-4efd-b9bf-c72e1e9172df'), primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.ForeignKey(db_column='image', on_delete=django.db.models.deletion.CASCADE, to='msproduct.image')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='msproduct.product')),
            ],
            options={
                'db_table': 'MAE_PRODUCT_IMAGE',
            },
        ),
    ]
