# Generated by Django 5.0.6 on 2024-06-07 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e5a35ed-9035-4456-a655-2792d1c546b7'), primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e5a35ed-9035-4456-a655-2792d1c546b7'), primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e5a35ed-9035-4456-a655-2792d1c546b7'), primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e5a35ed-9035-4456-a655-2792d1c546b7'), primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e5a35ed-9035-4456-a655-2792d1c546b7'), primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e5a35ed-9035-4456-a655-2792d1c546b7'), primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e5a35ed-9035-4456-a655-2792d1c546b7'), primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e5a35ed-9035-4456-a655-2792d1c546b7'), primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
