# Generated by Django 5.0.6 on 2024-06-21 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msemailmodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47235bc7-b13a-4020-982d-d9d8f9b7a4b7'), primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
