name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    # services:
    #   db:
    #     image: postgres:14.2-alpine
    #   env:
    #     POSTGRES_DB: demo
    #     POSTGRES_USER: demo
    #     POSTGRES_PASSWORD: demo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install backend/src/requirements/development.txt

      - name: Run Tests
        working-directory: ./backend
        run: pytest

  deply:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Hello world
        run: echo hello world
